### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic Tensor (Round:0) to a numpy array.

### ISSUE THREAD

**Issue by mindmad** [billymoonxd/ResUNet#1]
Hello  @billymoonxd ,
I got this error when I try to test my model. 

 ```
0%|          | 0/1695 [00:03<?, ?it/s]
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-5-9674fbeec897> in <module>
      4 batch_size = 8
      5 model_path = "ResUNet/logs/ckpt/20211122-080409-0028-loss0.51.h5"  # Replace with your model path
----> 6 test(model_path, training_dataset="unet-crackSeg/data/crack_segmentation_dataset")

<ipython-input-4-3080886b203e> in test(model_path, training_dataset)
     75 #             save_path = f"results/{training_dataset}_X_{test_dataset}/test/resultResunet/"
     76 
---> 77     evaluate(model_path, test_dataset_path=test_dataset_path, save_path=save_path, cross_dataset=False)

<ipython-input-4-3080886b203e> in evaluate(model_path, test_dataset_path, save_path, cross_dataset)
     49     model = load_model_weights(model_path)
     50     model.evaluate(test_dataset, steps=test_steps)
---> 51     write_result(model, test_x, test_y, save_path)
     52 
     53 

<ipython-input-4-3080886b203e> in write_result(model, test_x, test_y, save_path)
     27             x[0], sep_line,
     28             mask_to_3c(y), sep_line,
---> 29             mask_to_3c(y_pred)
     30         ]
     31         all_images = [*map(lambda x: x * 255., all_images)]

<ipython-input-4-3080886b203e> in mask_to_3c(mask)
      3     Convert single-channel mask to 3-channel (288, 384, 1) -> (288, 384, 3).
      4     """
----> 5     mask = np.repeat(mask, 3, axis=-1)
      6     return mask
      7 

<__array_function__ internals> in repeat(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in repeat(a, repeats, axis)
    477 
    478     """
--> 479     return _wrapfunc(a, 'repeat', repeats, axis=axis)
    480 
    481 

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     53     bound = getattr(obj, method, None)
     54     if bound is None:
---> 55         return _wrapit(obj, method, *args, **kwds)
     56 
     57     try:

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     42     except AttributeError:
     43         wrap = None
---> 44     result = getattr(asarray(obj), method)(*args, **kwds)
     45     if wrap:
     46         if not isinstance(result, mu.ndarray):

/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     81 
     82     """
---> 83     return array(a, dtype, copy=False, order=order)
     84 
     85 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py in __array__(self)
    734   def __array__(self):
    735     raise NotImplementedError("Cannot convert a symbolic Tensor ({}) to a numpy"
--> 736                               " array.".format(self.name))
    737 
    738   def __len__(self):

NotImplementedError: Cannot convert a symbolic Tensor (Round:0) to a numpy array.
```

any help in this matter

**Comment by billymoonxd** [comment]
This may be a compatibility issue between numpy, python, and tensorflow.
I'm using numpy 1.19.5, python 3.7.11, tensorflow-gpu 2.6.0, and did not meet the problem.

Here is a post for your information: https://github.com/tensorflow/models/issues/9706

**Comment by mindmad** [comment]
@billymoonxd  thank you for your response after I change the tf version it worked fine.

However, the prediction images are not corresponding to the original image. is there any advice on this matter?

**Comment by billymoonxd** [comment]
Hi, mindmad. Do you mean that **y_pred** and **y_true** do not match?
Yet the image and the corresponding mask are bundled together by _tf.data.Dataset.from_tensor_slices( )_.

Could you give me a better picture of your problem?

**Comment by mindmad** [comment]
hello @billymoonxd , I appreciate your help.

exactly the y_preed and y_true do not match. first, the output of the test function was like this :
![0](https://user-images.githubusercontent.com/15253812/143396855-0ad0122c-d839-4ea1-8a4a-4290581be204.png)

I did not understand what cause  the model to show this result even though my evaluation output is this:
`212/212 [==============================] - 69s 324ms/step - loss: 0.3108 - dice_coef: 0.6896 - mean_io_u_1: 0.6760 - recall_1: 0.5278 - precision_1: 0.8981` 
 put after reinstalling tf and the rest of the library it shows me like this
![02](https://user-images.githubusercontent.com/15253812/143397558-f77b8ad7-4023-4a0b-8528-2f6e2297dccd.png)
my work is on crack detection, and the predicted image is corrspand to other image in the test images

**Comment by billymoonxd** [comment]
Hi mindmad. I also have no idea why _y_pred_ goes that far from _y_true_, but **_transposed y_pred_** is closer to _y_true_ in some way.

Are there any **normal** predictions in your results (or after applying **transposition**)?
Does your model have multiple outputs (since I noticed _mean_io_u_1_, _recall_1_, and _precision_1_ in your output)?

Well, if not, **maybe** the model you're using does not perform well in your application, as the evaluation metrics show.

**Comment by mindmad** [comment]
> Are there any **normal** predictions in your results (or after applying **transposition**)? 

I thought about applying transposition manually or inside the evaluation function, however, the shape of the  y-pred does not match with the y_true , and that y_pred corresponds to another image . which means its predicted right but misordered the result 

>Does your model have multiple outputs (since I noticed _mean_io_u_1_, _recall_1_, and _precision_1_ in your output)?

I was confused when it first show me this output in the training I did not add any multiple outputs. so I have been searching for the course of it.  until I found out that I add the AUC metric to the metric variable. and I used an old model to load its wights. so it shows like that. then I start training without loading old models wights. the output return to normal.



> Well, if not, **maybe** the model you're using does not perform well in your application, as the evaluation metrics show.

I am not sure if the model is or is not suitable for my task but like the images I showed, there are many y-pred corresponds to other y_true.

**Comment by billymoonxd** [comment]
Hi mindmad. According to your description, your predictions are acceptable but **transposed** and **disordered** somehow.

As far as I know, there is not any transposition operations except in the data augmentation process, and the tf dataset ensures that images and corresponding masks are bundled together.

Please give special attention to these issues when troubleshooting.

**Comment by mindmad** [comment]
hi @billymoonxd , I appreciate your help and support.
I tried a different method for loading and evaluate the data and it worked fine. 
however, I want to enter my image as gray to the model if possible can you provide me with advice on what I need to modify in the model.

**Comment by billymoonxd** [comment]
Deal with grayscale images the same way as with binary masks : )

**Comment by mindmad** [comment]
before i commented and ask you in here, I have modified the loading of the dataset for the train_x and valid_x to be as the train_y and valid_y and change the shape to (288, 384, 1)  however it still shows me an error of wrong input detention (I didn't safe the output error and now am training once i finish i will implement it and show the error here)
so is there anything am missing not to modify.
